package com.nscorps.ipl;

import com.nscorps.ipl.dao.IPLDAO;
import com.nscorps.ipl.dto.CaptainDTO;
import com.nscorps.ipl.dto.IPLDTO;

public class TestIPL {
	
	public static void main(String[] args) {
		IPLDTO ipldetailsDTO=new IPLDTO();
		IPLDTO ipldetailsDTO1=new IPLDTO();
		
		ipldetailsDTO.setTeamName("Royal challengers bangalore");
		ipldetailsDTO.setNoOfPlayers((byte)16);
		ipldetailsDTO.setViseCaptain("ABDeviliers");
		ipldetailsDTO.setOwner("United Spirits");
		
		
		ipldetailsDTO1.setTeamName("Mumbai_indians");
		ipldetailsDTO1.setNoOfPlayers((byte)11);
		ipldetailsDTO1.setViseCaptain("Sharma");
		ipldetailsDTO1.setOwner("Ambani");
		
		CaptainDTO dto=new CaptainDTO();
		dto.setCaptainName("VIRAT KOHLI");
		dto.setAucPriceinCr((byte)17);
		dto.setExperience("14 yrs of experience");
		CaptainDTO dto1=new CaptainDTO();
		dto1.setCaptainName("Rohith Sharma");
		dto1.setAucPriceinCr((byte)20);
		dto1.setExperience("20 yrs of experience");
		
		ipldetailsDTO.setCaptain(dto);
		ipldetailsDTO1.setCaptain(dto1);
		
		
		
		System.out.println(ipldetailsDTO.getTeamName());
		System.out.println(dto1.getAucPriceinCr());
		System.out.println();
		
		IPLDAO dao = new IPLDAO();
		dao.add(ipldetailsDTO);
		dao.add(ipldetailsDTO1);
		dao.printAll();
		
		 System.out.println("teamname updated by owner");
		 IPLDTO ipldetailsdto=dao.updateteamNamebyOwner("United Spirits", "RCB");
	     System.out.println(ipldetailsdto.toString());
	     dao.printAll();
	     
	     

		 System.out.println("noOfplayers updated by visecaptain");
		 System.out.println();
		 IPLDTO ipldetailsdto1=dao.updatenoOfPlayersbyViseCaptain((byte)12,"Sharma");
	     System.out.println(ipldetailsdto1.toString());
	     dao.printAll();
	     
	     System.out.println("data generated by teamName");
	     IPLDTO res=dao.getbyteamName("RCB");
	     System.out.println(res);
	     
	    System.out.println("data generated by experience");
		IPLDTO res1=dao.getbyExperience("20 yrs of experience");
		System.out.println(res1);
		
		
		   System.out.println("data deleted by owner");
			IPLDTO resp1=dao.deletebyowner("AMBANI");
			System.out.println(resp1);
			dao.printAll();
		
	}
}
